#!/bin/bash
echo "Precommit hook is running..."
USER_NAME="oleksandr-dudnyk"
ESLINT_MOBILE="$(git rev-parse --show-toplevel)/mobile/node_modules/.bin/eslint"
TSLINT_BACKEND="$(git rev-parse --show-toplevel)/server/node_modules/.bin/tslint"

MOBILE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(^mobile)(.*)(ts$|tsx$)')
BACKEND_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(^server)(.*)(ts$)')
PASS=true

echo "=============================================================================================================="
echo "Checking branch name..."

echo "\t\033[32m Success! \033[0m"

exit $?